export const orders = [
  {
    id: 1,
    short_description: "Documents",
    order_type: "motoroller",
    from_town: "Estremoz Madonna Mia Porto Estremoz Estremoz Madonna Mia Porto Estremoz Madonna Mia Porto Estremoz Estremoz Madonna Mia Porto",
    from_date: "13.08.2024",
    from_time: "23:00",
    to_town: "Estremoz Madonna Mia Porto Lisboa",
    to_date: "13.09.2024",
    to_time: "22:00",
    price: "15€",
  },
  {
    id: 1,
    short_description: "Box",
    order_type: "car",
    from_town: "Estremoz Lassida",
    from_date: "29.08.2024",
    from_time: "18:00",
    to_town: "Estremoz Lassida",
    to_date: "13.09.2024",
    to_time: "22:00",
    price: "110€",
  },
  {
    id: 1,
    short_description: "Food",
    order_type: "truck",
    from_town: "Estremoz Madonna Mia Porto",
    from_date: "14.08.2024",
    from_time: "09:00",
    to_town: "Estremoz Madonna Mia Porto",
    to_date: "13.09.2024",
    to_time: "22:00",
    price: "7€",
  },
];
